var myAge=21;
var earlyYears=2;
earlyYears*=10.5;
laterYears=myAge-2;
laterYears*=4;
console.log(earlyYears,laterYears);
var myAgeInDogYears=earlyYears+laterYears;
let text="RANJITH";
let myName=text.toLowerCase();
console.log(`My name is ${myName}. I am ${myAge} old in human years which is ${myAgeInDogYears} years old in dog years.`);